name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-versions: [ '8.1', '8.2' ]
        allow-failure: [ false ]
        coverage: [ false ]
        composer-flags: [ '' ]
        include:
          - php-versions: '8.1'
            coverage: true
          - php-versions: '8.2'
            allow-failure: true
            composer-flags: '--ignore-platform-req php'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install system dependencies
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: xdebug

      - name: Validate composer
        run: composer validate

      - name: Cache composer dependencies
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-${{ matrix.php-versions }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.php-versions }}-composer-

      - name: Install composer dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress --no-suggest ${{ matrix.composer-flags }}

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse

      - name: Run PHP-CS-Fixer
        continue-on-error: ${{ matrix.allow-failure }}
        env:
          PHP_CS_FIXER_IGNORE_ENV: ${{ matrix.allow-failure }}
        run: vendor/bin/php-cs-fixer fix --dry-run --diff --verbose

      - name: Run PHPunit
        env:
          TMDB_API_TOKEN: ${{ secrets.TMDB_API_TOKEN }}
          XDEBUG_MODE: coverage
        run: vendor/bin/phpunit

      - name: Upload tests coverage
        if: ${{ matrix.coverage }}
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./build
